# Generated by Django 4.2.10 on 2024-02-21 11:58

import os

from django.contrib.auth.models import User
from django.db import migrations


class CreateSuperAdmin(migrations.RunPython):

    def __init__(self):
        super().__init__(self.create_admin_user, self.delete_admin_user)

    def create_admin_user(*args):
        email = os.environ.get("ADMIN_EMAIL", "admin@example.com")
        password = os.environ.get("ADMIN_PASSWORD", "admin")
        User.objects.create_superuser("admin", email, password)

    def delete_admin_user(*arg):
        User.objects.get(username='admin').delete()



class Migration(migrations.Migration):
    initial = True
    operations = [
        CreateSuperAdmin(),
    ]