# Generated by Django 5.1.2 on 2024-10-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='describe',
        ),
        migrations.AddField(
            model_name='alert',
            name='annotations',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='fingerprint',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='labels',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='values',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('FIRING', 'FIRING'), ('RESOLVED', 'RESOLVED')], default='UNKNOWN', max_length=20, null=True),
        ),
    ]
