# Generated by Django 5.1.2 on 2024-10-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_remove_alert_describe_alert_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='server',
        ),
    ]
