# Generated by Django 5.1.2 on 2024-11-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_remove_alert_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
